<?php require "views/header.phtml"; ?>
    <div class="login pets">
        <div class="login-content">
            <p>Admin Panel</p>
        </div>
        
        <form action="<?php echo URL?>admin" method="post">
            <select id="export-to" name="exportorder">
                <option value="">Sort by:</option>
                <option value="byname">Name</option>
                <option value="bycatasc">Categories - Ascending</option>
                <option value="bycatdesc">Categories - Descending</option>
                <option value="bysignasc">Signatures - Ascending</option>
                <option value="bysigndesc">Signatures - Descending</option>
                <option value="bytargetdesc">Target - Descending</option>
                <option value="bytargetasc">Target - Ascending</option>
                <option value="bydateasc">Started date - Ascending</option>
                <option value="bydatedesc">Started date - Descending</option>
            </select>
            <select id="export-to" name="export">
                <option value="csv">CSV</option>
                <option value="pdf">PDF</option>
                <option value="html">HTML</option>
            </select>
            <button id="button-export" class="create-button" type="submit" name="exported" value="true">Export</button>
        </form>
        <button id="adm-all-pet">See all petitions</button>
        <button id="adm-all-usr">See all users</button>
        <br>
        <div id="admin-all-petitions" class="adm-all-pet hidden">
            <select id="foo">
                <option value="">Sort by:</option>
                <option value="<?php echo $_SERVER['REQUEST_URI']?>&sort=byname">Name</option>
                <option value="<?php echo $_SERVER['REQUEST_URI']?>&sort=bycatasc">Categories - Ascending</option>
                <option value="<?php echo $_SERVER['REQUEST_URI']?>&sort=bycatdesc">Categories - Descending</option>
                <option value="<?php echo $_SERVER['REQUEST_URI']?>&sort=bysignasc">Signatures - Ascending</option>
                <option value="<?php echo $_SERVER['REQUEST_URI']?>&sort=bysigndesc">Signatures - Descending</option>
                <option value="<?php echo $_SERVER['REQUEST_URI']?>&sort=bytargetdesc">Target - Descending</option>
                <option value="<?php echo $_SERVER['REQUEST_URI']?>&sort=bytargetasc">Target - Ascending</option>
                <option value="<?php echo $_SERVER['REQUEST_URI']?>&sort=bydateasc">Started date - Ascending</option>
                <option value="<?php echo $_SERVER['REQUEST_URI']?>&sort=bydatedesc">Started date - Descending</option>
            </select>
            <div class="clear"></div>
            <script>
                document.getElementById("foo").onclick = function() {
                    if (this.selectedIndex!==0) {
                        window.location.href = this.value;
                    }
                };
            </script>
            <div class="table-petitions my-petitions">
                <table class="table-columns" width="100%" align="center" cellpadding="0" cellspacing="1" border="0">
                    <thead>
                    <tr>
                        <th class="columnName1" align="left"><b>Name</b></th>
                        <th class="columnName" align="left"><b>Category</b></th>
                        <th class="columnName" align="left"><b>Signed</b></th>
                        <th class="columnName" align="left"><b>Target</b></th>
                        <th class="columnName" align="left"><b>Created on</b></th>
                        <th class="columnName" align="left"><b>Actions</b></th>
                    </tr>
                    </thead>
                </table>
                <hr>
                <table class="table-petdetails" width="100%" align="center" cellpadding="0" cellspacing="1" border="0">
                    <?php
                    $pets=$this->petdata;
                    foreach($pets as $row):?>
                        <tr>
                            <td class="petName" align="left"><a href="<?php echo URL?>petition/petitiondetail/<?php echo $row->getId()?>"><?php echo $row->getTitle();?></a></td>
                            <td class="atr-cell" align="left"><?php echo $row->getCategory();?></td>
                            <td class="atr-cell" align="left"><?php echo $row->getSigned();?></td>
                            <td class="atr-cell" align="left"><?php echo $row->getTarget();?></td>
                            <td class="atr-cell" allign="left"><span class="att-target"><?php echo date_format($row->getCreated(), 'Y-m-d');?></span></td>
                            <td class="atr-cell" align="left">    
                                <a href="<?php echo URL?>petition/edit/<?php echo $row->getId()?>">Edit</a>
                                <a href="<?php echo URL?>petition/delete/<?php echo $row->getId()?>">Delete</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
            <form action="" method="get">
                <?php
                if($this->petpagesExist):
                    foreach($this->petpages as $page):?>
                        <input type="submit" name="page" value="<?php echo $page?>">
                    <?php endforeach; endif; ?>
            </form>
        </div>
<!-- USERS -->
        <div class="table-petitions my-petitions adm-all-usr hidden">
            <table class="table-columns" width="100%" align="center" cellpadding="0" cellspacing="1" border="0">
                <thead>
                <tr>
                    <th class="columnName1" align="left"><b>Name</b></th>
                    <th class="columnName" align="left"><b>Email</b></th>
                    <th class="columnName" align="left"><b>Type</b></th>
                    <th class="columnName" align="left"><b>Birthdate</b></th>
                    <th class="columnName" align="left"><b>Country</b></th>
                    <!-- <th class="columnName" align="left"><b>Actions</b></th> -->
                </tr>
                </thead>
            </table>
            <hr>

            <table class="table-petdetails" width="100%" align="center" cellpadding="0" cellspacing="1" border="0">
                <?php
                $users=$this->userdata;
                foreach($users as $row):?>
                    <tr>
                        <td class="petName" id="users-cell" align="left"><?php echo $row->getName();?></td>
                        <td class="atr-cell" id="users-cell" align="left"><?php echo $row->getEmail();?></td>
                        <td class="atr-cell" id="users-cell" align="left"><?php echo $row->getType();?></td>
                        <td class="atr-cell" id="users-cell" align="left"><?php echo $row->getCountry();?></td>
                        <td class="atr-cell" id="users-cell" align="left"><?php echo date_format($row->getBirth(), 'Y-m-d');?></td>
<!--                        <td align="left"><a href="--><?php //echo URL?><!--petition/edit/--><?php //echo $row->getId()?><!--">Edit</a></td>-->
<!--                        <td align="left"><a href="--><?php //echo URL?><!--petition/delete/--><?php //echo $row->getId()?><!--">Delete</a></td>-->
                    </tr>
                <?php endforeach; ?>
            </table>
            <form action="<?php echo URL?>admin/index" method="get">
                <?php
                if($this->userpagesExist):
                    foreach($this->userpages as $page):?>
                        <input type="submit" name="page2" value="<?php echo $page?>">
                    <?php endforeach; endif; ?>
            </form>
        </div>    
    </div>
    <script type="text/javascript">
        $(document).ready(function(){
             $("#adm-all-usr").on("click",function(){
                $(".adm-all-pet").addClass("hidden");
                $(".adm-all-usr").removeClass("hidden");
            });
            $("#adm-all-pet").on("click",function(){
                $(".adm-all-usr").addClass("hidden");
                $(".adm-all-pet").removeClass("hidden");
            });
        });
    </script>
<?php require "views/footer.phtml"; ?>