<?php require "views/header.phtml"; ?>
    <div class="login" id="myAccount">
        <div class="login-content myAccount-content">
            <p id="welcome">Welcome to your account!</p>
            <div id="sub-welcome">
                <p> You can see your account details and change them.</p>
                <p> If you have created petitions, you can view, edit and/or delete them.</p>
            </div>    
            <button id="my-acc" class="my-acc-button">My Account</button>
            <button id="my-pet" class="my-acc-button">My Petitions</button>
        </div>
        <div class="login-content2 hidden" id="account-informations">  
            <span>Name: </span><?php echo $this->userdata->getName();?>
            <br><span>Email: </span><?php echo $this->userdata->getEmail();?>
            <br><span>Country: </span><?php echo $this->userdata->getCountry();?>
            <br><span>Birthdate: </span><?php echo date_format($this->userdata->getBirth(),"d/m/Y");?>
            <br><a class="change-button" href="<?php echo URL?>myaccount/update/">Change account details</a>
            <?php if($this->userdata->getType()=="admin"): ?>
                <br><a class="change-button" href="<?php echo URL?>admin">Admin Panel</a>
            <?php endif; ?>
        </div>
        <div class="login-content">
            
        </div>
        <div class="table-petitions my-petitions hidden">
            <table class="table-columns" width="100%" align="center" cellpadding="0" cellspacing="1" border="0">
                <thead>
                <tr>
                    <th class="columnName1" align="left"><b>Name</b></th>
                    <th class="columnName" align="left"><b>Category</b></th>
                    <th class="columnName" align="left"><b>Signed</b></th>
                    <th class="columnName" align="left"><b>Target</b></th>
                    <th class="columnName" align="left"><b>Created on</b></th>
                    <th class="columnName" align="left"><b>Actions</b></th>
                </tr>
                </thead>
            </table>
            <hr>
           <table class="table-petdetails" width="100%" align="center" cellpadding="0" cellspacing="1" border="0">
                <?php
                $pets=$this->data;
                foreach($pets as $row):?>
                    <tr>
                        <td class="petName" align="left"><a href="<?php echo URL?>petition/petitiondetail/<?php echo $row->getId()?>"><?php echo $row->getTitle();?></a></td>
                        <td class="atr-cell" align="left"><?php echo $row->getCategory();?></td>
                        <td class="atr-cell" align="left"><?php echo $row->getSigned();?></td>
                        <td class="atr-cell" align="left"><?php echo $row->getTarget();?></td>
                        <td class="atr-cell" align="left"><?php echo date_format($row->getCreated(), 'Y-m-d');?></td>
                        <td class="atr-cell" align="left">    
                            <a href="<?php echo URL?>petition/edit/<?php echo $row->getId()?>">Edit</a><span> | </span>
                            <a href="<?php echo URL?>petition/delete/<?php echo $row->getId()?>">Delete</a>
                            <div class="clear"></div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
            <form action="<?php echo URL?>myaccount/index" method="get">
                <?php
                if($this->pagesExist):
                foreach($this->pages as $page):?>
                    <input type="submit" name="page" value="<?php echo $page?>">
                <?php endforeach; endif; ?>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function() {
            // alert("haha");
            $("#my-acc").on("click",function(){
                $(".my-petitions").addClass("hidden");
                $(".login-content2").removeClass("hidden");
            });
            $("#my-pet").on("click",function(){
                $(".login-content2").addClass("hidden");
                $(".my-petitions").removeClass("hidden");
            });

        });
    </script>
<?php require "views/footer.phtml"; ?>