<?php require "views/header.phtml"; ?>
    <div class="content">
        <h1>My Account</h1>
        <br>
        Name:<?php echo $this->userdata->getName();?>
        <br>Country:<?php echo $this->userdata->getCountry();?>
        <br>Birthdate:<?php echo date_format($this->userdata->getBirth(),"d/m/Y");?>
        <br><a href="<?php echo URL?>myaccount/update/">Change email/password</a>
        <hr>
        <table width="80%" align="center" cellpadding="0" cellspacing="1" border="0">
            <thead>
            <tr>
                <th align="left"><b>Name</b></th>
                <th align="left"><b>Category</b></th>
                <th align="left"><b>Signed</b></th>
                <th align="left"><b>Target</b></th>
            </tr>
            </thead>
        </table>
        <hr>
        <table width="80%" align="center" cellpadding="0" cellspacing="1" border="0">
            <?php
            $pets=$this->data;
            foreach($pets as $row):?>
                <tr>
                    <td align="left"><a href="<?php echo URL?>petition/petitiondetail/<?php echo $row->getId()?>"><?php echo $row->getTitle();?></a></td>
                    <td align="left"><?php echo $row->getCategory();?></td>
                    <td align="left"><?php echo $row->getSigned();?></td>
                    <td align="left"><?php echo $row->getTarget();?></td>
                </tr>
            <?php endforeach; ?>
        </table>
        <form action="<?php echo URL?>myaccount/index" method="get">
            <?php
            if($this->pagesExist):
            foreach($this->pages as $page):?>
                <input type="submit" name="page" value="<?php echo $page?>">
            <?php endforeach; endif; ?>
            <hr>
            <a href="<?php echo URL?>">back to home page</a>
    </div>
<?php require "views/footer.phtml"; ?>