<?php require "views/header.phtml";?>
<div class="login">
    <div class="login-content2" id="account-informations">  
            <span>Name: </span><?php echo $this->userdata->getName();?>
            <br><span>Email: </span><?php echo $this->userdata->getEmail();?>
            <br><span>Country: </span><?php echo $this->userdata->getCountry();?>
            <br><span>Birthdate: </span><?php echo date_format($this->userdata->getBirth(),"d/m/Y");?> 
        </div>
        <form id="form-update"action="<?php echo URL?>myaccount/update" method="POST">
            <p class="form-title">Update user information</p>
            <span class="update-fields">*Current Password:</span> <input type="password"  name="pass" ><br>
            <span class="update-fields">New Name:</span> <input type="text" name="name2" ><br>
            <span class="update-fields">New Email:</span> <input type="email" name="email2" ><br>
            <span class="update-fields">New Birthdate:</span> <input type="text" pattern="([0][0-9]|[1][0-2])[/]([0][0-9]|[1][0-9]|[2][0-9]|[3][0-1])[/][1][9]([4-8][0-9]|[9][0-6])" name="date2"><br>
            <span class="update-fields">New Country:</span> <input type="text"  name="country2"><br>
            <span class="update-fields">New Password:</span> <input type="password" name="pass2"><br>
            <input class="submit-update" type="submit" name="submit" value="Submit">
        </form>
</div>            
<?php require "views/footer.phtml";?>