<!-- <!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="../public/css/footer.css" />
		<title></title>
	</head>
	<body>
 -->
	<div class="footer">
		<!-- <hr /> -->
	 	<div class="footer-content">
			<p>Copyright &copy;  2015 &nbsp;&nbsp;&nbsp;Lates Augustin &amp; Rosu Vladut</p>
			<ul class="follow-list">
				<li><small>FOLLOW US:</small></li>
				<li><a href="https://www.facebook.com/pet4webTW"><img src="<?php echo IMG?>facebook.png" ></a></li>
				<li><a href="#"><img src="<?php echo IMG?>twitter.png"></a></li>
				<li><a href="#"><img src="<?php echo IMG?>google.png"></a></li>
				<div class="clear"></div>
			</ul>
			<!-- <div class="clear"></div> -->
		</div>
		<!-- <div class="clear"></div> -->
	</div> 	
	</body>
</html>