<div class="home-content">
	<div class="petitions-box">
		<h3>Start an online petition and get your message heard </h3>
		<div class="petition-options">
			<div class="create-petition section-box">
				<p><strong>pet4Web</strong> is the easy way to start a petition and make your voice heard by governments and business leaders all over the world.</p>
				<a href="<?php echo URL?>petition/newpetition">Create new petition</a>
			</div>
			<div class="sign-petition section-box">
				<p>There is also the possibility that your views, shared by others, was already included in an online petition posted on <strong>pet4Web</strong>.</p>
				<a href="<?php echo URL?>petition/index">Sign a petition</a>
			</div>	
		</div>		
		<!-- <a href="<?php echo URL?>help">help!!!</a> -->
		<?php // echo "<br />" . $this->message;?>
	</div>
	<div class="clear"></div>
</div>