<?php require "views/header.phtml"; ?>
<div class="login">
    <div class="login-content2 edit-pet-details" id="petition-informations">
        <span>Name: </span><?php echo $this->data->getTitle()?><br>
        <span>Category: </span><?php echo $this->data->getCategory()?><br>
        <span>Message: </span><?php echo $this->data->getMessage()?><br>
        <span>Target: </span><?php echo $this->data->getTarget()?><br>
        <span>Signatures: </span><?php echo $this->data->getSigned()?><br>
    </div>    
</div>
    <div class="content2">
        <form id="form-update" action="<?php echo URL?>petition/edit/<?php echo $this->data->getId()?>" method="post">
            <p class="form-title">Edit petition</p>
            <label><span class="update-fields" id ="field-pet">Name: </span></label><input type="text" name="name" value=""/>
            <br>
            <label><span class="update-fields" id ="field-pet">Message: </span></label><input type="text" name="message" value=""/>
            <br>
            <label><span class="update-fields" id ="field-pet">Category: </span></label>
            <select name="category">
                    <option value="Human Rights">Human Rights</option>
                    <option value="Environment">Environment</option>
                    <option value="Faith and Religion">Faith and Religion</option>
                    <option value="Politics">Politics</option>
                    <option value="Heallth">Health</option>
                    <option value="Education">Education</option>
                    <option value="Media and Culture">Media and Culture</option>
                </select>
            <br>
            <label><span class="update-fields" id ="field-pet">Target: <span></label><input type="number" name="target" value=""/>
            <br>
            <button class="submit-update" type="submit">Edit</button>
        </form>
    </div>
<?php require "views/footer.phtml"; ?>    