<?php require "views/header.phtml"; ?>
    <div class="login">
        <div class="login-content">
            <p>Create new petition</p>
        </div>  
        <!-- <h2>Create new petition</h2> -->
        <div class="login-content2">
            <form action="<?php echo URL?>/petition/newpetition" method="post">
                <label><span>Name:</span></label><input type="text" name="name" title="Please, use only letters, numbers, white spaces and be sure you have a length greater than 6" value=""/>
                <br>
                <label><span>Message:</span></label><input type="text" required pattern="[!@#$%^&*()_-+=:;<,.>/1-9a-zA-Z ]{10}[!@#$%^&*()_-+=:;<,.>/1-9a-zA-Z ]*" title="Please, use only letters, white spaces, digits and be sure you have a length greater than 10" name="message" value=""/>
                <br>
                <label><span>Category:</span></label>
                <select name="category">
                    <option value="Human Rights">Human Rights</option>
                    <option value="Environment">Environment</option>
                    <option value="Faith and Religion">Faith and Religion</option>
                    <option value="Politics">Politics</option>
                    <option value="Heallth">Health</option>
                    <option value="Education">Education</option>
                    <option value="Media and Culture">Media and Culture</option>
                </select>
                <br>
                <label><span>Target:</span></label><input type="number" name="target" value=""/>
                <br>
                <button class="create-button" type="submit">Create</button>
            </form>
        </div>                
    </div>
        <!-- <a href="<?php echo URL?>">back to home page</a> -->
<?php require "views/footer.phtml"; ?>