
	<div class="login">
		<div class="login-content">
			<p>Login</p>
		</div>	
		<div class="arrow bounce hidden">
		</div>
		<div class="login-content2">
			<form action="<?php echo URL?>login/in" method="post">
				<label><span>Email:</span></label><input type="email" name="username" value="" required pattern="[a-zA-Z1-9]+[@][a-zA-Z1-9]+[.][a-zA-Z1-9]+" title="Please, provide an e-mail"/><br>
				<label><span>Password:</span></label><input type="password" name="passwd" value="" />
				<br>
				<button class="submit" type="submit">Submit</button><br>
				<button  class="no-account" type="button">Don't Have an Account?</button><br>
				<a class="log-register hidden" href="<?php echo URL?>login/register">Register</a>
			</form>
		</div>
	</div>
	<script type="text/javascript">
			$(document).ready(function(){
				var $window = $(window);
				var windowsize = $window.width();
					function responsiveWidth() {	
						if (windowsize < 800) {
							$(".no-account").on("click",function() {
								$(".log-register").addClass("hidden");
								$(".log-register").removeClass("hidden");
							});
						}
						else {
							$(".no-account").on("click",function(){
							$(".arrow").addClass("hidden");
							$(".arrow").removeClass("hidden");
							});
						}
					};
				responsiveWidth();
			});
		</script>
<!-- </body>
</html>	 -->