<?php require "views/header.phtml"; ?>
<?php if(isset($this->ErrorMessage)):?><div class="content red"><?php echo $this->ErrorMessage?></div><?php endif?>
<div class="login">
	<div class="login-content">
			<p>Register</p>
	</div>
	<div class="login-content2">
		<form action="<?php echo URL?>/login/register" method="post">
			<label><span>Email:</span></label><input type="email" name="username" value=""/><br>
			<label><span>Password:</span></label><input type="password" name="passwd" value=""/><br>
			<label><span>Name:</span></label><input type="text" name="name" value=""/><br>
			<label><span>Country:</span></label><input type="text" name="country" value=""/><br>
			<label><span>Birthdate:</span></label><input type="date" name="date" value=""/><br>
			<button class="submit" type="submit">Register</button>
		</form>
	</div>
</div>
<?php require "views/footer.phtml"; ?>